name: get-flag

on:
  push:
    branches: [corgi]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  recon:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::009661764077:role/cicdRole
          aws-region: us-east-1

      - name: Get current bucket policy
        run: |
          aws s3api get-bucket-policy --bucket codec4f26c862a321ef5 --query Policy --output text | python3 -m json.tool
